import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import "bootstrap/dist/css/bootstrap.css";

import SideMenu from "./components/sideBar/SideMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideMenu>{children}</SideMenu>
      </body>
    </html>
  );
}
